USE adlister_db;

DROP TABLE IF EXISTS ads;
CREATE TABLE IF NOT EXISTS ads(
id int UNSIGNED NOT NULL AUTO_INCREMENT,
user_id int UNSIGNED NOT NULL,
title VARCHAR (100) NOT NULL,
description TEXT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);